# Site settings
title: Joseph (Jin-Chuan) Tang
email: jinntrance@gmail.com
url: josephjctang.com
description: "This is the homepage of Joseph Jin-Chuan Tang."

# Color settings (hex-codes without the leading hash-tag)
# change the setting in _sass/grayscale
color:
  primary-dark: Black
  links: '#219ab3'

# wheather enable Google resources
google: false

# Footer settings
footer: Joseph

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/josephjinchuantang
  - title: github
    url: https://github.com/jinntrance/
  - title: weibo
    url: http://weibo.com/jinntrance/
  - title: douban
    url: http://www.douban.com/people/jinntrance/
  - title: google-plus
    url: https://google.com/+JosephJinChuanT%C3%A1ng
    
# Build settings
markdown: redcarpet
permalink: pretty
sass:
  style: compressed
redcarpet:
    extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]

include: [".htaccess"]

compress_html:
  clippings: all
  comments: ["<!-- "," -->"]
  endings: all
  ignore:
    envs: []

compress_js:
  clippings: all
  comments: [["/* "," */"]]

